project:
  type: book
  output-dir: _output

book:
  title: "我的 Quarto 書籍測試"
  author: "IT 老菜鳥"
  date: last-modified
  date-format: "yyyy-MM-dd"
  chapters:
    - index.qmd
    - 01-intro.qmd
    - 02-workflow.qmd
    - references.qmd

lang: zh-TW
toc: true
number-sections: true

format:
  html:
    theme: cosmo
    code-line-numbers: true
  epub:
    toc: true
    code-line-numbers: true
  pdf:    
    include-in-header: custom.tex
    documentclass: book    
    papersize: a4
    toc: true
    toc-depth: 3
    number-sections: true
    linestretch: 1.3 # 列高
    # 指定Noto Serif CJK TC)
    mainfont: "Noto Serif CJK TC"    
    #CJKmainfont: "Microsoft JhengHei"
    monofont: "Fira Code" # 注意：程式碼區塊中的中文會顯示成豆腐!
    fontsize: 11pt
    monofontoptions: "Scale=0.8"
    code-line-numbers: true    
