name: Build and Deploy Quarto Book

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout 專案
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. 安裝 Quarto CLI
      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: "latest"

      # 3. 安裝 LaTeX（生成 PDF）
      - name: Setup TinyTeX
        uses: r-lib/actions/setup-tinytex@v2

      # 4. 安裝中文字體（避免 PDF 缺字）
      - name: Install CJK fonts
        run: |
          sudo apt-get update
          sudo apt-get install -y fonts-noto-cjk

      # 5. 渲染 Quarto 書籍 (HTML + PDF)
      - name: Render book
        run: quarto render

      # 6. 上傳 PDF 作為 artifact（方便下載檢查）
      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: quarto-book-pdf
          path: _book/*.pdf

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: "latest"

      - name: Render book (HTML only)
        run: quarto render --to html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _book
